### ISSUE TITLE
Nickname command doesn't work from console

### ISSUE THREAD

**Issue by WizardCM** [WMCAlliance/RoyalCommands#3]
```
[16:26:09 WARN]: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_13_R2.command.ColouredConsoleSender cannot be cast to org.bukkit.OfflinePlayer
[16:26:09 WARN]:        at org.royaldev.royalcommands.rcommands.CmdNick.runCommand(CmdNick.java:99)
[16:26:09 WARN]:        at org.royaldev.royalcommands.rcommands.CACommand.runCommand(CACommand.java:23)
[16:26:09 WARN]:        at org.royaldev.royalcommands.rcommands.BaseCommand.onCommand(BaseCommand.java:282)
[16:26:09 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[16:26:09 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139)
[16:26:09 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:699)
[16:26:09 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:684)
[16:26:09 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.aU(DedicatedServer.java:459)
[16:26:09 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:418)
[16:26:09 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
[16:26:09 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
[16:26:09 WARN]:        at java.lang.Thread.run(Unknown Source)
```

**Comment by BlaneyXYZ** [comment]
Fixed :)
